### ISSUE TITLE
Panic on Uninitialized Database

### ISSUE THREAD

**Issue by benyanke** [jubnzv/go-taskwarrior#1]
Receive the following error when running without an initialized taskwarrior database, instead of a proper error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e4c2c]

goroutine 1 [running]:
github.com/jubnzv/go-taskwarrior.(*TaskWarrior).FetchAllTasks(0x0, 0x9, 0x0)
	/home/[me]/gocode/src/github.com/jubnzv/go-taskwarrior/taskwarrior.go:40 +0x2c
main.main()
	/home/[me]/gocode/src/path/to/me/taskwarriorclient/main.go:10 +0x49
```

**Comment by jubnzv** [comment]
Nice catch, thank you @benyanke.
